# Generated by Django 4.2.4 on 2023-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=10)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('DOB', models.CharField(max_length=35)),
                ('SelectMembershipplan', models.CharField(max_length=250)),
                ('SelectTrainer', models.CharField(max_length=50)),
                ('Reference', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=25)),
                ('salary', models.IntegerField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
