# Generated by Django 4.2.4 on 2023-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selectdate', models.DateTimeField(auto_now_add=True)),
                ('Login', models.CharField(max_length=150)),
                ('Logout', models.CharField(max_length=100)),
                ('SelectWorkout', models.CharField(max_length=200)),
                ('TrainBy', models.CharField(max_length=100)),
            ],
        ),
    ]
