# Generated by Django 4.2.4 on 2023-08-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_attendance_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='TrainBy',
        ),
        migrations.AddField(
            model_name='attendance',
            name='TrainedBy',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Login',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Logout',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='DOB',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='FullName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Gender',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='PhoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Reference',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipplan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectTrainer',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan',
            field=models.CharField(max_length=185),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(max_length=55),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(max_length=25),
        ),
    ]
